config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'caches#index'

  post '/set_cache', to: 'caches#set_cache'
  get '/retrieve_cache', to: 'caches#retrieve_cache'

  get '/health', to: (proc { [200, {}, []] })
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Localization
end

app/controllers/caches_controller.rb
# frozen_string_literal: true

class CachesController < ApplicationController
  def index; end

  def set_cache
    Rails.cache.write(params[:key], params[:value])
  end

  def retrieve_cache
    render :index, locals: { cache_key: params[:key], cache_value: Rails.cache.read(params[:key]) }
  end
end

app/controllers/concerns/localization.rb
# frozen_string_literal: true

module Localization
  extend ActiveSupport::Concern

  included do
    around_action :switch_locale

    protected

    def switch_locale(&action)
      locale = extract_locale_from_param || I18n.default_locale

      I18n.with_locale(locale, &action)
    end

    def extract_locale_from_param
      return params[:locale] if I18n.locale_available?(params[:locale])

      nil
    end

    private

    def default_url_options
      { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/caches_helper.rb
module CachesHelper
end

app/views/caches/index.html.erb
<h1>REDIS_URL: <%= ENV["REDIS_URL"] %></h1>

<%= form_tag(set_cache_path, method: :post) do %>
  <%= label_tag :key, 'Cache Key' %>
  <%= text_field_tag :key %>

  <%= label_tag :value, 'Cache Value' %>
  <%= text_field_tag :value %>

  <%= submit_tag 'Set Cache' %>
<% end %>

<%= form_tag(retrieve_cache_path, method: :get) do %>
  <%= label_tag :key, 'Cache Key' %>
  <%= text_field_tag :key %>

  <%= submit_tag 'Retrieve Cache' %>
<% end %>

<% if local_assigns[:cache_key] || local_assigns[:cache_value] %>
  <h1>Cache key: <%= local_assigns[:cache_key] %></h1>
  <h1>Cache value: <%= local_assigns[:cache_value] %></h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
  <head>
    <title>NimbleDevopsIcWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

  <body>
    <%= yield %>
  </body>
</html>